export class MetadataService {
  constructor(client) { this.client = client; this._sobjects = null; }
  async listApexClasses() { const { records } = await this.client.toolingQuery(`SELECT Id, Name, ApiVersion, Status, LastModifiedDate, LastModifiedBy.Name FROM ApexClass ORDER BY Name`, { all: true }); return records.map((r) => this._node(r, "ApexClass")); }
  async listApexTriggers() { const { records } = await this.client.toolingQuery(`SELECT Id, Name, ApiVersion, Status, TableEnumOrId, LastModifiedDate, LastModifiedBy.Name FROM ApexTrigger ORDER BY Name`, { all: true }); return records.map((r) => ({ ...this._node(r, "ApexTrigger"), sobject: r.TableEnumOrId })); }
  async listVisualforcePages() { const { records } = await this.client.toolingQuery(`SELECT Id, Name, ApiVersion, MasterLabel, LastModifiedDate, LastModifiedBy.Name FROM ApexPage ORDER BY Name`, { all: true }); return records.map((r) => this._node(r, "ApexPage")); }
  async listVisualforceComponents() { const { records } = await this.client.toolingQuery(`SELECT Id, Name, ApiVersion, MasterLabel, LastModifiedDate, LastModifiedBy.Name FROM ApexComponent ORDER BY Name`, { all: true }); return records.map((r) => this._node(r, "ApexComponent")); }
  async listLwcBundles() { const { records } = await this.client.toolingQuery(`SELECT Id, DeveloperName, MasterLabel, ApiVersion, Description, LastModifiedDate, LastModifiedBy.Name FROM LightningComponentBundle ORDER BY DeveloperName`, { all: true }); return records.map((r) => ({ id: r.Id, name: r.DeveloperName, type: "LightningComponentBundle", apiVersion: r.ApiVersion, status: "Active", lastModifiedBy: r.LastModifiedBy && r.LastModifiedBy.Name, lastModifiedDate: r.LastModifiedDate })); }
  async listAuraBundles() { const { records } = await this.client.toolingQuery(`SELECT Id, DeveloperName, MasterLabel, ApiVersion, Description, LastModifiedDate, LastModifiedBy.Name FROM AuraDefinitionBundle ORDER BY DeveloperName`, { all: true }); return records.map((r) => ({ id: r.Id, name: r.DeveloperName, type: "AuraDefinitionBundle", apiVersion: r.ApiVersion, status: "Active", lastModifiedBy: r.LastModifiedBy && r.LastModifiedBy.Name, lastModifiedDate: r.LastModifiedDate })); }
  async listStaticResources() { const { records } = await this.client.query(`SELECT Id, Name, ContentType, BodyLength, LastModifiedDate FROM StaticResource ORDER BY Name`, { all: true }); return records.map((r) => ({ id: r.Id, name: r.Name, type: "StaticResource", contentType: r.ContentType, size: r.BodyLength, lastModifiedDate: r.LastModifiedDate, status: "Active" })); }
  async listSObjects() { if (this._sobjects) return this._sobjects; const res = await this.client.describeGlobal(); const list = (res.sobjects || []).filter((s) => s.createable || s.triggerable).map((s) => s.name).sort((a, b) => a.localeCompare(b)); this._sobjects = list; return list; }
  async openApexLike(node) { const map = { ApexClass: { obj: "ApexClass", ext: "cls", lang: "apex" }, ApexTrigger: { obj: "ApexTrigger", ext: "trigger", lang: "apex" }, ApexPage: { obj: "ApexPage", ext: "page", lang: "html" }, ApexComponent: { obj: "ApexComponent", ext: "component", lang: "html" } }[node.type]; const rec = await this.client.toolingRetrieve(map.obj, node.id, ["Body", "ApiVersion", "Name"]); return [{ key: `${node.type}:${node.id}`, name: `${rec.Name || node.name}.${map.ext}`, ext: map.ext, language: map.lang, body: rec.Body || "", memberType: node.type, recordId: node.id, apiVersion: rec.ApiVersion }]; }
  async openLwcBundle(node) { const { records } = await this.client.toolingQuery(`SELECT Id, FilePath, Format, Source FROM LightningComponentResource WHERE LightningComponentBundleId = '${node.id}'`, { all: true }); return records.map((r) => ({ key: `LwcResource:${r.Id}`, name: r.FilePath.split("/").pop(), path: r.FilePath, ext: extOf(r.FilePath), language: langFor(r.FilePath), body: r.Source || "", memberType: "LightningComponentBundle", bundleId: node.id, recordId: r.Id, format: r.Format })).sort(bundleSort); }
  async openAuraBundle(node) { const { records } = await this.client.toolingQuery(`SELECT Id, DefType, Format, Source FROM AuraDefinition WHERE AuraDefinitionBundleId = '${node.id}'`, { all: true }); return records.map((r) => ({ key: `AuraDef:${r.Id}`, name: `${node.name}${auraSuffix(r.DefType, r.Format)}`, ext: (r.Format || "js").toLowerCase(), language: langFor(`x.${(r.Format || "js").toLowerCase()}`), body: r.Source || "", memberType: "AuraDefinitionBundle", bundleId: node.id, recordId: r.Id, defType: r.DefType, format: r.Format })).sort(bundleSort); }
  async openStaticResource(node) { const res = await this.client.request(`/services/data/v${this.client.apiVersion}/sobjects/StaticResource/${node.id}/Body`, { raw: true }); const buf = await res.arrayBuffer(); let body = ""; try { body = new TextDecoder().decode(buf); } catch (_) { body = "(binary content)"; } return [{ key: `StaticResource:${node.id}`, name: node.name, ext: "resource", language: "text", body, memberType: "StaticResource", recordId: node.id }]; }
  async open(node) { switch (node.type) { case "ApexClass": case "ApexTrigger": case "ApexPage": case "ApexComponent": return this.openApexLike(node); case "LightningComponentBundle": return this.openLwcBundle(node); case "AuraDefinitionBundle": return this.openAuraBundle(node); case "StaticResource": return this.openStaticResource(node); default: throw new Error(`Cannot open ${node.type}`); } }
  _node(r, type) { return { id: r.Id, name: r.Name || r.MasterLabel || r.DeveloperName, type, apiVersion: r.ApiVersion, status: r.Status || "Active", lastModifiedBy: r.LastModifiedBy && r.LastModifiedBy.Name, lastModifiedDate: r.LastModifiedDate }; }
}
function extOf(p) { const s = p.split("."); return s.length > 1 ? s.pop() : ""; }
function langFor(p) { const e = extOf(p).toLowerCase(); if (e === "js") return "javascript"; if (["html","cmp","app","evt"].includes(e)) return "html"; if (e === "css") return "css"; if (e === "xml") return "xml"; return "text"; }
function bundleSort(a, b) { const o = { js: 0, html: 1, css: 2, xml: 3 }; return (o[a.ext] ?? 9) - (o[b.ext] ?? 9) || a.name.localeCompare(b.name); }
function auraSuffix(d, f) { const m = { COMPONENT: ".cmp", APPLICATION: ".app", EVENT: ".evt", INTERFACE: ".intf", CONTROLLER: "Controller.js", HELPER: "Helper.js", RENDERER: "Renderer.js", STYLE: ".css", DOCUMENTATION: ".auradoc", DESIGN: ".design", SVG: ".svg" }; return m[d] || `.${(f || "js").toLowerCase()}`; }
